select
    sk_dateid as sk_date_id,
    datevalue as date_value,
    datedesc as date_desc,
    calendaryearid as calendar_year_id,
    calendaryeardesc as calendar_year_desc,
    calendarqtrid as calendar_qtr_id,
    calendarqtrdesc as calendar_qtr_desc,
    calendarmonthid as calendar_month_id,
    calendarmonthdesc as calendar_month_desc,
    calendarweekid as calendar_week_id,
    calendarweekdesc as calendar_week_desc,
    dayofweeknum as day_of_week_num,
    dayofweekdesc as day_of_week_desc,
    fiscalyearid as fiscal_year_id,
    fiscalyeardesc as fiscal_year_desc,
    fiscalqtrid as fiscal_qtr_id,
    fiscalqtrdesc as fiscal_qtr_desc,
    holidayflag as holiday_flag
from tpcdi.batch1_date
