-- Bronze: read prospect from staging table (all loaded batches)
select
    agencyid as agency_id,
    lastname as last_name,
    firstname as first_name,
    middleinitial as middle_initial,
    gender,
    addressline1 as address_line1,
    addressline2 as address_line2,
    postalcode as postal_code,
    city,
    state,
    country,
    phone,
    income,
    numbercars as number_cars,
    numberchildren as number_children,
    maritalstatus as marital_status,
    age,
    creditrating as credit_rating,
    ownorrentflag as own_or_rent_flag,
    employer,
    numbercreditcards as number_credit_cards,
    networth as net_worth
from tpcdi.staging_prospect
